// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArrr-zFV0by3UKSRNj_ILgd0A3TeAwTXk',
    appId: '1:616195707231:web:4dd7da00f476ba7544e6ea',
    messagingSenderId: '616195707231',
    projectId: 'whiskeyai',
    authDomain: 'whiskeyai.firebaseapp.com',
    storageBucket: 'whiskeyai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHB3sUdskMvltZCfwTpWlstrmPv-dicPY',
    appId: '1:616195707231:android:86fb41ca12d65f0344e6ea',
    messagingSenderId: '616195707231',
    projectId: 'whiskeyai',
    storageBucket: 'whiskeyai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGjJOy0zw26P3Z6n84jFlL_A_G39hvX8',
    appId: '1:616195707231:ios:e5026e1b1adaf7f744e6ea',
    messagingSenderId: '616195707231',
    projectId: 'whiskeyai',
    storageBucket: 'whiskeyai.appspot.com',
    iosClientId: '616195707231-k0gu1ld95md89mvnej63aim1c78ig38l.apps.googleusercontent.com',
    iosBundleId: 'com.spacedsoft.com.whiskeyai',
  );
}
